POST http://localhost:8000/products/1/lowest-price
Content-Type: application/json
Accept: application/json
# force_fail: 400

{
  "quantity": -5,
  "request_location": "UK",
  "voucher_code": "OU812",
  "request_date": "2025-02-04",
  "product_id": 1
}

### another
GET https://google.com/